--Create the CUSTOMER_INVOICE database
CREATE SCHEMA CUSTOMER_INVOICE;
USE CUSTOMER_INVOICE;

--Create CUSTOMER table
CREATE TABLE CUSTOMER (
CUST_NUM INT,
CUST_LNAME VARCHAR(30),
CUST_FNAME VARCHAR(30),
CUST_BALANCE DECIMAL(8,2),
PRIMARY KEY (CUST_NUM)
);

DESCRIBE CUSTOMER;

CREATE INVOICE (
INV_NUM INT,
CUST_NUM INT,
INV_DATE DATE,
INV_AMOUNT DECIMAL(10,2),
PRIMARY KEY (INV_NUM)
);

ALTER TABLE INVOICE ADD CONSTRAINT fk_INVOICE FOREIGN KEY (CUST_NUM)
REFERENCES CUSTOMER (CUST_NUM) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO CUSTOMER (CUST_NUM, CUST_LNAME, CUST_FNAME, CUST_BALANCE) VALUES
(1000, 'Smith', 'Jeanne', 1050.11),
(                                );

INSERT INTO INVOICE VALUES
(8000, 1000, '2016-03-23', 235,89),
(                          ),
(                          ),
(                          );

SELECT DATE_FORMAT(INV_DATE, '%d %b %y')
FROM INVOICE;

